// 核心战法
const coreSkill = [
  {
    name: '单骑救主',
    pinyin: 'danqijiuzhu',
    skill_id: 200862,
    skill_mark_type: [4],
    skill_quality_level: 'A',
    skill_type: 2,
  },
  {
    name: '河内世泽',
    pinyin: 'heneishize',
    skill_id: 200847,
    skill_mark_type: [2],
    skill_quality_level: 'S',
    skill_type: 3,
  },
  {
    name: '人中吕布',
    pinyin: 'renzhonglvbu',
    skill_id: 200834,
    skill_mark_type: [1],
    skill_quality_level: 'A',
    skill_type: 3,
  },
  {
    name: '桃园结义',
    pinyin: 'taoyuanjieyi',
    skill_id: 200784,
    skill_mark_type: [2, 3],
    skill_quality_level: 'S',
    skill_type: 2,
  },
  {
    name: '兵无常势',
    pinyin: 'bingwuchangshi',
    skill_id: 200766,
    skill_mark_type: [3, 4],
    skill_quality_level: 'A',
    skill_type: 1,
  },
  {
    name: '始计',
    pinyin: 'shiji',
    skill_id: 200687,
    skill_mark_type: [4],
    skill_quality_level: 'S',
    skill_type: 2,
  },
  {
    name: '一骑当千',
    pinyin: 'yiqidangqian',
    skill_id: 200647,
    skill_mark_type: [1],
    skill_quality_level: 'S',
    skill_type: 3,
  },
  {
    name: '浑水摸鱼',
    pinyin: 'hunshuimoyu',
    skill_id: 200235,
    skill_mark_type: [4],
    skill_quality_level: 'S',
    skill_type: 3,
  },
  {
    name: '战必断金',
    pinyin: 'zhanbiduanjin',
    skill_id: 200228,
    skill_mark_type: [4],
    skill_quality_level: 'S',
    skill_type: 2,
  },
  {
    name: '反计之策',
    pinyin: 'fanjizhice',
    skill_id: 200220,
    skill_mark_type: [4],
    skill_quality_level: 'S',
    skill_type: 2,
  },
  {
    name: '神兵天降',
    pinyin: 'shenbingtianjiang',
    skill_id: 200204,
    skill_mark_type: [4],
    skill_quality_level: 'S',
    skill_type: 2,
  },
  {
    name: '大赏三军',
    pinyin: 'dashangsanjun',
    skill_id: 200198,
    skill_mark_type: [4],
    skill_quality_level: 'S',
    skill_type: 2,
  },
  {
    name: '久战熟谋',
    pinyin: 'jiuzhanshumou',
    skill_id: 200959,
    skill_mark_type: [4],
    skill_quality_level: 'A',
    skill_type: 2,
  },
  {
    name: '及锋而试',
    pinyin: 'jifengershi',
    skill_id: 200979,
    skill_mark_type: [1],
    skill_quality_level: 'S',
    skill_type: 3,
  },
];

// 重要战法
const halfCoreSkill = [
  {
    name: '避其锋芒',
    pinyin: 'biqifengmang',
    skill_id: 200194,
    skill_mark_type: [4],
    skill_quality_level: 'S',
    skill_type: 2,
  },
  {
    name: '无心恋战',
    pinyin: 'wuxinlianzhan',
    skill_id: 200201,
    skill_mark_type: [4],
    skill_quality_level: 'S',
    skill_type: 2,
  },
  {
    name: '妖术',
    pinyin: 'yaoshu',
    skill_id: 200237,
    skill_mark_type: [4],
    skill_quality_level: 'S',
    skill_type: 3,
  },
  {
    name: '不攻',
    pinyin: 'bugong',
    skill_id: 200622,
    skill_mark_type: [4],
    skill_quality_level: 'S',
    skill_type: 2,
  },
  {
    name: '深谋远虑',
    pinyin: 'shenmouyuanlv',
    skill_id: 200645,
    skill_mark_type: [4],
    skill_quality_level: 'A',
    skill_type: 1,
  },
  {
    name: '愈战愈勇',
    pinyin: 'yuzhanyuyong',
    skill_id: 200643,
    skill_mark_type: [4],
    skill_quality_level: 'A',
    skill_type: 1,
  },
  {
    name: '十面埋伏',
    pinyin: 'shimianmaifu',
    skill_id: 200715,
    skill_mark_type: [2],
    skill_quality_level: 'S',
    skill_type: 3,
  },
  {
    name: '胜兵求战',
    pinyin: 'shengbingqiuzhan',
    skill_id: 200754,
    skill_mark_type: [4],
    skill_quality_level: 'B',
    skill_type: 2,
  },
  {
    name: '重整旗鼓',
    pinyin: 'chongzhengqigu',
    skill_id: 200757,
    skill_mark_type: [3],
    skill_quality_level: 'S',
    skill_type: 2,
  },
  {
    name: '枭雄',
    pinyin: 'xiaoxiong',
    skill_id: 200788,
    skill_mark_type: [4],
    skill_quality_level: 'B',
    skill_type: 1,
  },
  {
    name: '凤仪亭',
    pinyin: 'fengyiting',
    skill_id: 200789,
    skill_mark_type: [1, 4],
    skill_quality_level: 'A',
    skill_type: 3,
  },
  {
    name: '众谋不懈',
    pinyin: 'zhongmoubuxie',
    skill_id: 200800,
    skill_mark_type: [2],
    skill_quality_level: 'S',
    skill_type: 2,
  },
  {
    name: '利兵谋胜',
    pinyin: 'libingmousheng',
    skill_id: 200801,
    skill_mark_type: [2, 3],
    skill_quality_level: 'S',
    skill_type: 3,
  },
  {
    name: '形兵之极',
    pinyin: 'xingbingzhiji',
    skill_id: 200813,
    skill_mark_type: [4],
    skill_quality_level: 'B',
    skill_type: 2,
  },
  {
    name: '汜水关',
    pinyin: 'sishuiguan',
    skill_id: 200814,
    skill_mark_type: [1],
    skill_quality_level: 'A',
    skill_type: 3,
  },
  {
    name: '鼎足江东',
    pinyin: 'dingzujiangdong',
    skill_id: 200844,
    skill_mark_type: [3],
    skill_quality_level: 'A',
    skill_type: 3,
  },
  {
    name: '美人计',
    pinyin: 'meirenji',
    skill_id: 200853,
    skill_mark_type: [4],
    skill_quality_level: 'B',
    skill_type: 2,
  },
  {
    name: '三军之众',
    pinyin: 'sanjunzhizhong',
    skill_id: 200886,
    skill_mark_type: [3],
    skill_quality_level: 'S',
    skill_type: 3,
  },
  {
    name: '当阳桥',
    pinyin: 'dangyangqiao',
    skill_id: 200888,
    skill_mark_type: [4],
    skill_quality_level: 'S',
    skill_type: 3,
  },
  {
    name: '威震逍遥',
    pinyin: 'weizhenxiaoyao',
    skill_id: 200926,
    skill_mark_type: [1],
    skill_quality_level: 'A',
    skill_type: 3,
  },
  {
    name: '飒沓如星',
    pinyin: 'sataruxing',
    skill_id: 200929,
    skill_mark_type: [4],
    skill_quality_level: 'B',
    skill_type: 3,
  },
  {
    name: '三术奇谋',
    pinyin: 'sanshujimou',
    skill_id: 200938,
    skill_mark_type: [2],
    skill_quality_level: 'S',
    skill_type: 3,
  },
  {
    name: '势无虚动',
    pinyin: 'shiwuxudong',
    skill_id: 200949,
    skill_mark_type: [4],
    skill_quality_level: 'A',
    skill_type: 1,
  },
  {
    name: '望风而降',
    pinyin: 'wangfengerjiang',
    skill_id: 200982,
    skill_mark_type: [2],
    skill_quality_level: 'A',
    skill_type: 3,
  },
];

// 亮点战法
const starSkill = [
  {
    name: '乘胜追击',
    pinyin: 'chengshengzhuiji',
    skill_id: 200980,
    skill_mark_type: [1],
    skill_quality_level: 'S',
    skill_type: 4,
  },
  {
    name: '百战无怯',
    pinyin: 'baizhanwuqie',
    skill_id: 200252,
    skill_mark_type: [4],
    skill_quality_level: 'S',
    skill_type: 1,
  },
  {
    name: '攻其不备',
    pinyin: 'gongqibubei',
    skill_id: 200755,
    skill_mark_type: [4],
    skill_quality_level: 'S',
    skill_type: 2,
  },
  {
    name: '垒实迎击',
    pinyin: 'leishiyingji',
    skill_id: 200900,
    skill_mark_type: [4],
    skill_quality_level: 'S',
    skill_type: 1,
  },
  {
    name: '击势',
    pinyin: 'jishi',
    skill_id: 200863,
    skill_mark_type: [4],
    skill_quality_level: 'S',
    skill_type: 1,
  },
  {
    name: '正始之变',
    pinyin: 'zhengshizhibian',
    skill_id: 200244,
    skill_mark_type: [4],
    skill_quality_level: 'S',
    skill_type: 2,
  },
];

export const eightSkillId = [...starSkill].map((item) => item.skill_id); // 10分列表

export const fiveSkillId = [...coreSkill].map((item) => item.skill_id); // 5分列表

export const threeSkillId = [...halfCoreSkill].map((item) => item.skill_id); // 5分列表
