// 绝版核心
export const jueCore = [
  {
    country: '5',
    hero_id: 100479,
    hero_type: 1,
    icon_hero_id: 100479,
    name: '吕布',
    pinyin: 'lvbu',
    quality: 5,
    season: 'S2',
    star: 5,
  },
  {
    country: '3',
    hero_id: 100496,
    hero_type: 1,
    icon_hero_id: 100496,
    name: '诸葛亮',
    pinyin: 'zhugeliang',
    quality: 5,
    season: 'S3',
    star: 5,
  },
];

// 三皇
export const huang = [
  {
    country: '2',
    hero_id: 100023,
    hero_type: 3,
    icon_hero_id: 100023,
    name: '曹操',
    pinyin: 'caocao',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '3',
    hero_id: 100016,
    hero_type: 2,
    icon_hero_id: 100016,
    name: '刘备',
    pinyin: 'liubei',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '4',
    hero_id: 100030,
    hero_type: 1,
    icon_hero_id: 100030,
    name: '孙权',
    pinyin: 'sunquan',
    quality: 5,
    season: 'N',
    star: 5,
  },
];

// 核心
export const core = [
  {
    country: '4',
    hero_id: 100035,
    hero_type: 1,
    icon_hero_id: 100035,
    name: '吕蒙',
    pinyin: 'lvmeng',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '5',
    hero_id: 100013,
    hero_type: 3,
    icon_hero_id: 100013,
    name: '马超',
    pinyin: 'machao',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '1',
    hero_id: 100526,
    hero_type: 1,
    icon_hero_id: 100526,
    name: '张机',
    pinyin: 'zhangji',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '2',
    hero_id: 100028,
    hero_type: 1,
    icon_hero_id: 100028,
    name: '王异',
    pinyin: 'wangyi',
    quality: 5,
    season: 'N',
    star: 5,
  },
];

// 半核心
export const halfCore = [
  {
    country: '5',
    hero_id: 100337,
    hero_type: 2,
    icon_hero_id: 100337,
    name: '貂蝉',
    pinyin: 'diaochan',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '6',
    hero_id: 100703,
    hero_type: 2,
    icon_hero_id: 100703,
    name: '司马炎',
    pinyin: 'simayan',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '2',
    hero_id: 100027,
    hero_type: 3,
    icon_hero_id: 100027,
    name: '张辽',
    pinyin: 'zhangliao',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '3',
    hero_id: 100649,
    hero_type: 2,
    icon_hero_id: 100649,
    name: '魏延',
    pinyin: 'weiyan',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '5',
    hero_id: 100372,
    hero_type: 2,
    icon_hero_id: 100372,
    name: '妲己',
    pinyin: 'daji',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '5',
    hero_id: 100474,
    hero_type: 2,
    icon_hero_id: 100474,
    name: '张宁',
    pinyin: 'zhangning',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '6',
    hero_id: 100705,
    hero_type: 1,
    icon_hero_id: 100705,
    name: '杜预',
    pinyin: 'duyu',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '2',
    hero_id: 100618,
    hero_type: 1,
    icon_hero_id: 100618,
    name: '贾诩',
    pinyin: 'jiaxu',
    quality: 5,
    season: 'N',
    star: 5,
  },
];

// XP核心
export const xpCore = [
  {
    country: '3',
    hero_id: 100451,
    hero_type: 3,
    icon_hero_id: 100451,
    name: '关羽',
    pinyin: 'guanyu',
    quality: 5,
    season: 'XP',
    star: 5,
  },
  {
    country: '4',
    hero_id: 100619,
    hero_type: 2,
    icon_hero_id: 100619,
    name: '大乔',
    pinyin: 'daqiao',
    quality: 5,
    season: 'XP',
    star: 5,
  },
  {
    country: '3',
    hero_id: 100615,
    hero_type: 3,
    icon_hero_id: 100615,
    name: '马岱',
    pinyin: 'madai',
    quality: 5,
    season: 'XP',
    star: 5,
  },
  {
    country: '5',
    hero_id: 100670,
    hero_type: 1,
    icon_hero_id: 100670,
    name: '袁绍',
    pinyin: 'yuanshao',
    quality: 5,
    season: 'XP',
    star: 5,
  },
];

// XP半核心
export const xpHalfCore = [
  {
    country: '4',
    hero_id: 100784,
    hero_type: 2,
    icon_hero_id: 100784,
    name: '周瑜',
    pinyin: 'zhouyu',
    quality: 5,
    season: 'XP',
    star: 5,
  },
  {
    country: '3',
    hero_id: 100631,
    hero_type: 3,
    icon_hero_id: 100631,
    name: '严颜',
    pinyin: 'yanyan',
    quality: 5,
    season: 'XP',
    star: 5,
  },
  {
    country: '5',
    hero_id: 100692,
    hero_type: 3,
    icon_hero_id: 100692,
    name: '田丰',
    pinyin: 'tianfeng',
    quality: 5,
    season: 'XP',
    star: 5,
  },
  {
    country: '5',
    hero_id: 100443,
    hero_type: 1,
    icon_hero_id: 100443,
    name: '陈宫',
    pinyin: 'chengong',
    quality: 5,
    season: 'XP',
    star: 5,
  },
  {
    country: '5',
    hero_id: 100604,
    hero_type: 1,
    icon_hero_id: 100604,
    name: '李儒',
    pinyin: 'liru',
    quality: 5,
    season: 'XP',
    star: 5,
  },
  {
    country: '1',
    hero_id: 100675,
    hero_type: 1,
    icon_hero_id: 100675,
    name: '刘表',
    pinyin: 'liubiao',
    quality: 5,
    season: 'XP',
    star: 5,
  },
  {
    country: '1',
    hero_id: 100630,
    hero_type: 2,
    icon_hero_id: 100630,
    name: '皇甫嵩',
    pinyin: 'huangfusong',
    quality: 5,
    season: 'XP',
    star: 5,
  },
];

// 普通绝版
export const jue = [
  {
    country: '2',
    hero_id: 100476,
    hero_type: 3,
    icon_hero_id: 100476,
    name: '郭嘉',
    pinyin: 'guojia',
    quality: 5,
    season: 'S2',
    star: 5,
  },
  {
    country: '4',
    hero_id: 100478,
    hero_type: 2,
    icon_hero_id: 100478,
    name: '陆逊',
    pinyin: 'luxun',
    quality: 5,
    season: 'S2',
    star: 5,
  },
  {
    country: '3',
    hero_id: 100477,
    hero_type: 2,
    icon_hero_id: 100477,
    name: '庞统',
    pinyin: 'pangtong',
    quality: 5,
    season: 'S2',
    star: 5,
  },
  {
    country: '1',
    hero_id: 100480,
    hero_type: 2,
    icon_hero_id: 100480,
    name: '董卓',
    pinyin: 'dongzhuo',
    quality: 5,
    season: 'S2',
    star: 5,
  },
  {
    country: '2',
    hero_id: 100498,
    hero_type: 3,
    icon_hero_id: 100498,
    name: '曹纯',
    pinyin: 'caochun',
    quality: 5,
    season: 'S3',
    star: 5,
  },
];

// 有用卡池
export const useful = [
  {
    country: '5',
    hero_id: 100677,
    hero_type: 3,
    icon_hero_id: 100677,
    name: '公孙瓒',
    pinyin: 'gongsunzan',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '3',
    hero_id: 100072,
    hero_type: 2,
    icon_hero_id: 100072,
    name: '关银屏',
    pinyin: 'guanyinping',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '4',
    hero_id: 100574,
    hero_type: 2,
    icon_hero_id: 100574,
    name: '陆抗',
    pinyin: 'lukang',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '1',
    hero_id: 100770,
    hero_type: 1,
    icon_hero_id: 100770,
    name: '许劭',
    pinyin: 'xushao',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '6',
    hero_id: 100701,
    hero_type: 3,
    icon_hero_id: 100701,
    name: '司马师',
    pinyin: 'simashi',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '6',
    hero_id: 100702,
    hero_type: 3,
    icon_hero_id: 100702,
    name: '司马昭',
    pinyin: 'simazhao',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '6',
    hero_id: 100704,
    hero_type: 3,
    icon_hero_id: 100704,
    name: '文鸯',
    pinyin: 'wenyang',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '3',
    hero_id: 100582,
    hero_type: 3,
    icon_hero_id: 100582,
    name: '法正',
    pinyin: 'fazheng',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '3',
    hero_id: 100021,
    hero_type: 2,
    icon_hero_id: 100021,
    name: '赵云',
    pinyin: 'zhaoyun',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '3',
    hero_id: 102001,
    hero_type: 2,
    icon_hero_id: 100021,
    name: '赵云SP',
    pinyin: 'zhaoyun',
    quality: 5,
    season: 'SP',
    star: 5,
  },

  {
    country: '5',
    hero_id: 100771,
    hero_type: 2,
    icon_hero_id: 100771,
    name: '沮授',
    pinyin: 'jushou',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '5',
    hero_id: 100620,
    hero_type: 3,
    icon_hero_id: 100620,
    name: '张绣',
    pinyin: 'zhangxiu',
    quality: 5,
    season: 'XP',
    star: 5,
  },
  {
    country: '2',
    hero_id: 100672,
    hero_type: 3,
    icon_hero_id: 100672,
    name: '曹植',
    pinyin: 'caozhi',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '2',
    hero_id: 100475,
    hero_type: 2,
    icon_hero_id: 100475,
    name: '郝昭',
    pinyin: 'haozhao',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '3',
    hero_id: 100534,
    hero_type: 3,
    icon_hero_id: 100534,
    name: '徐庶',
    pinyin: 'xushu',
    quality: 5,
    season: 'SP',
    star: 5,
  },
  {
    country: '4',
    hero_id: 100589,
    hero_type: 2,
    icon_hero_id: 100589,
    name: '周泰',
    pinyin: 'zhoutai',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '3',
    hero_id: 100022,
    hero_type: 3,
    icon_hero_id: 100022,
    name: '张飞',
    pinyin: 'zhangfei',
    quality: 5,
    season: 'N',
    star: 5,
  },

  {
    country: '5',
    hero_id: 100377,
    hero_type: 1,
    icon_hero_id: 100377,
    name: '骊姬',
    pinyin: 'chiji',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '5',
    hero_id: 100376,
    hero_type: 3,
    icon_hero_id: 100376,
    name: '褒姒',
    pinyin: 'baosi',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '5',
    hero_id: 100374,
    hero_type: 3,
    icon_hero_id: 100374,
    name: '妺喜',
    pinyin: 'moxi',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '5',
    hero_id: 100494,
    hero_type: 3,
    icon_hero_id: 100494,
    name: '祝融夫人',
    pinyin: 'zhurongfuren',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '3',
    hero_id: 102016,
    hero_type: 3,
    icon_hero_id: 100494,
    name: '祝融夫人',
    pinyin: 'zhurongfuren',
    quality: 5,
    season: 'SP',
    star: 5,
  },
  {
    country: '4',
    hero_id: 100450,
    hero_type: 3,
    icon_hero_id: 100450,
    name: '孙策',
    pinyin: 'sunce',
    quality: 5,
    season: 'XP',
    star: 5,
  },
  {
    country: '5',
    hero_id: 100452,
    hero_type: 3,
    icon_hero_id: 100452,
    name: '木鹿大王',
    pinyin: 'muludaiwang',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '5',
    hero_id: 102014,
    hero_type: 3,
    icon_hero_id: 100008,
    name: '张角SP',
    pinyin: 'zhangjiao',
    quality: 5,
    season: 'SP',
    star: 5,
  },
  {
    country: '1',
    hero_id: 100553,
    hero_type: 1,
    icon_hero_id: 100553,
    name: '朱儁',
    pinyin: 'zhujun',
    quality: 5,
    season: 'SP',
    star: 5,
  },
  {
    country: '2',
    hero_id: 100645,
    hero_type: 3,
    icon_hero_id: 100645,
    name: '徐晃',
    pinyin: 'xuhuang',
    quality: 5,
    season: 'XP',
    star: 5,
  },
  {
    country: '5',
    hero_id: 100647,
    hero_type: 3,
    icon_hero_id: 100647,
    name: '华雄',
    pinyin: 'huaxiong',
    quality: 5,
    season: 'XP',
    star: 5,
  },
  {
    country: '4',
    hero_id: 100648,
    hero_type: 1,
    icon_hero_id: 100648,
    name: '张昭',
    pinyin: 'zhangzhao',
    quality: 5,
    season: 'XP',
    star: 5,
  },
  {
    country: '3',
    hero_id: 100653,
    hero_type: 2,
    icon_hero_id: 100653,
    name: '关兴＆张苞',
    pinyin: 'guanxingzhangbao',
    quality: 5,
    season: 'XP',
    star: 5,
  },
  {
    country: '5',
    hero_id: 100656,
    hero_type: 3,
    icon_hero_id: 100656,
    name: '高顺',
    pinyin: 'gaoshun',
    quality: 5,
    season: 'XP',
    star: 5,
  },
  {
    country: '1',
    hero_id: 100676,
    hero_type: 3,
    icon_hero_id: 100676,
    name: '王昭君',
    pinyin: 'wangzhaojun',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '2',
    hero_id: 100685,
    hero_type: 2,
    icon_hero_id: 100685,
    name: '乐进',
    pinyin: 'yuejin',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '4',
    hero_id: 100687,
    hero_type: 1,
    icon_hero_id: 100687,
    name: '小乔',
    pinyin: 'xiaoqiao',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '3',
    hero_id: 100689,
    hero_type: 2,
    icon_hero_id: 100689,
    name: '刘禅',
    pinyin: 'liuchan',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '5',
    hero_id: 100690,
    hero_type: 1,
    icon_hero_id: 100690,
    name: '西施',
    pinyin: 'xishi',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '6',
    hero_id: 100706,
    hero_type: 1,
    icon_hero_id: 100706,
    name: '王元姬',
    pinyin: 'wangyuanji',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '6',
    hero_id: 100707,
    hero_type: 2,
    icon_hero_id: 100707,
    name: '卫瓘',
    pinyin: 'weiguan',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '6',
    hero_id: 100708,
    hero_type: 2,
    icon_hero_id: 100708,
    name: '贾充',
    pinyin: 'jiachong',
    quality: 5,
    season: 'XP',
    star: 5,
  },
  {
    country: '6',
    hero_id: 100709,
    hero_type: 2,
    icon_hero_id: 100709,
    name: '羊祜',
    pinyin: 'yanghu',
    quality: 5,
    season: 'XP',
    star: 5,
  },
  {
    country: '4',
    hero_id: 100741,
    hero_type: 2,
    icon_hero_id: 100741,
    name: '鲁肃',
    pinyin: 'lusu',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '1',
    hero_id: 100742,
    hero_type: 1,
    icon_hero_id: 100742,
    name: '阴丽华',
    pinyin: 'yinlihua',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '3',
    hero_id: 102012,
    hero_type: 1,
    icon_hero_id: 100074,
    name: '姜维SP',
    pinyin: 'jiangwei',
    quality: 5,
    season: 'SP',
    star: 5,
  },
  {
    country: 5,
    hero_id: 100785,
    hero_type: 3,
    icon_hero_id: 100785,
    name: '马腾',
    pinyin: 'mateng',
    quality: 5,
    season: 'N',
    star: 5,
  },
];

// 普通卡池
export const normal = [
  {
    country: 4,
    hero_id: 100788,
    hero_type: 2,
    icon_hero_id: 100788,
    name: '丁奉',
    pinyin: 'dingfeng',
    quality: 5,
    season: 'XP',
    star: 5,
  },
  {
    country: '5',
    hero_id: 100015,
    hero_type: 1,
    icon_hero_id: 100015,
    name: '甄洛',
    pinyin: 'zhenluo',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '5',
    hero_id: 102005,
    hero_type: 1,
    icon_hero_id: 100015,
    name: '甄洛',
    pinyin: 'zhenluo',
    quality: 5,
    season: 'SP',
    star: 5,
  },
  {
    country: '1',
    hero_id: 100002,
    hero_type: 1,
    icon_hero_id: 100002,
    name: '十常侍',
    pinyin: 'shichangshi',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '4',
    hero_id: 100497,
    hero_type: 2,
    icon_hero_id: 100497,
    name: '步皇后',
    pinyin: 'buhuanghou',
    quality: 5,
    season: 'S3',
    star: 5,
  },
  {
    country: '5',
    hero_id: 100495,
    hero_type: 3,
    icon_hero_id: 100495,
    name: '颜良＆文丑',
    pinyin: 'yanliangwenchou',
    quality: 5,
    season: 'S3',
    star: 5,
  },
  {
    country: '4',
    hero_id: 100424,
    hero_type: 2,
    icon_hero_id: 100424,
    name: '小乔＆大乔',
    pinyin: 'xiaoqiaodaqiao',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '5',
    hero_id: 100008,
    hero_type: 3,
    icon_hero_id: 100008,
    name: '张角',
    pinyin: 'zhangjiao',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '3',
    hero_id: 100020,
    hero_type: 2,
    icon_hero_id: 100020,
    name: '黄月英',
    pinyin: 'huangyueying',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '4',
    hero_id: 100031,
    hero_type: 1,
    icon_hero_id: 100031,
    name: '周瑜',
    pinyin: 'zhouyu',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '2',
    hero_id: 100024,
    hero_type: 3,
    icon_hero_id: 100024,
    name: '荀彧',
    pinyin: 'xunyu',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '2',
    hero_id: 100583,
    hero_type: 2,
    icon_hero_id: 100583,
    name: '荀攸',
    pinyin: 'xunyou',
    quality: 5,
    season: 'SP',
    star: 5,
  },
  {
    country: '4',
    hero_id: 100034,
    hero_type: 2,
    icon_hero_id: 100034,
    name: '甘宁',
    pinyin: 'ganning',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '1',
    hero_id: 100101,
    hero_type: 1,
    icon_hero_id: 100101,
    name: '灵帝',
    pinyin: 'lingdi',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '1',
    hero_id: 100003,
    hero_type: 3,
    icon_hero_id: 100003,
    name: '吕布',
    pinyin: 'lvbu',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '5',
    hero_id: 100593,
    hero_type: 3,
    icon_hero_id: 100593,
    name: '张郃',
    pinyin: 'zhangxia',
    quality: 5,
    season: 'XP',
    star: 5,
  },
  {
    country: '1',
    hero_id: 100005,
    hero_type: 1,
    icon_hero_id: 100005,
    name: '貂蝉',
    pinyin: 'diaochan',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '3',
    hero_id: 100019,
    hero_type: 3,
    icon_hero_id: 100019,
    name: '马云禄',
    pinyin: 'mayunlu',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '4',
    hero_id: 100032,
    hero_type: 1,
    icon_hero_id: 100032,
    name: '周姬',
    pinyin: 'zhouji',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '4',
    hero_id: 102017,
    hero_type: 2,
    icon_hero_id: 100032,
    name: '周姬',
    pinyin: 'zhouji',
    quality: 5,
    season: 'SP',
    star: 5,
  },
  {
    country: '4',
    hero_id: 100033,
    hero_type: 2,
    icon_hero_id: 100033,
    name: '孙坚',
    pinyin: 'sunjian',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '4',
    hero_id: 100036,
    hero_type: 1,
    icon_hero_id: 100036,
    name: '孙尚香',
    pinyin: 'sunshangxiang',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '3',
    hero_id: 102015,
    hero_type: 1,
    icon_hero_id: 100036,
    name: '孙尚香',
    pinyin: 'sunshangxiang',
    quality: 5,
    season: 'SP',
    star: 5,
  },
  {
    country: '5',
    hero_id: 100011,
    hero_type: 2,
    icon_hero_id: 100011,
    name: '贾诩',
    pinyin: 'jiaxu',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '3',
    hero_id: 100017,
    hero_type: 2,
    icon_hero_id: 100017,
    name: '诸葛亮',
    pinyin: 'zhugeliang',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '2',
    hero_id: 100029,
    hero_type: 1,
    icon_hero_id: 100029,
    name: '张春华',
    pinyin: 'zhangchunhua',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '1',
    hero_id: 100037,
    hero_type: 1,
    icon_hero_id: 100037,
    name: '何太后',
    pinyin: 'hetaihou',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '3',
    hero_id: 100074,
    hero_type: 2,
    icon_hero_id: 100074,
    name: '姜维',
    pinyin: 'jiangwei',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '2',
    hero_id: 100026,
    hero_type: 3,
    icon_hero_id: 100026,
    name: '关羽',
    pinyin: 'guanyu',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '1',
    hero_id: 100004,
    hero_type: 3,
    icon_hero_id: 100004,
    name: '蔡文姬',
    pinyin: 'caiwenji',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '1',
    hero_id: 102011,
    hero_type: 2,
    icon_hero_id: 100004,
    name: '蔡文姬',
    pinyin: 'caiwenji',
    quality: 5,
    season: 'SP',
    star: 5,
  },
  {
    country: '4',
    hero_id: 100090,
    hero_type: 1,
    icon_hero_id: 100090,
    name: '太史慈',
    pinyin: 'taishici',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '4',
    hero_id: 102003,
    hero_type: 1,
    icon_hero_id: 100090,
    name: '太史慈',
    pinyin: 'taishici',
    quality: 5,
    season: 'SP',
    star: 5,
  },
  {
    country: '2',
    hero_id: 100472,
    hero_type: 2,
    icon_hero_id: 100472,
    name: '司马懿',
    pinyin: 'simayi',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '2',
    hero_id: 100435,
    hero_type: 3,
    icon_hero_id: 100435,
    name: '夏侯渊',
    pinyin: 'xiahouyuan',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '2',
    hero_id: 102002,
    hero_type: 3,
    icon_hero_id: 100435,
    name: '夏侯渊',
    pinyin: 'xiahouyuan',
    quality: 5,
    season: 'SP',
    star: 5,
  },
  {
    country: '3',
    hero_id: 100442,
    hero_type: 2,
    icon_hero_id: 100442,
    name: '黄忠',
    pinyin: 'huangzhong',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '3',
    hero_id: 100358,
    hero_type: 1,
    icon_hero_id: 100358,
    name: '张姬',
    pinyin: 'zhangji',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '5',
    hero_id: 100488,
    hero_type: 2,
    icon_hero_id: 100488,
    name: '孟获',
    pinyin: 'menghuo',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '3',
    hero_id: 100524,
    hero_type: 1,
    icon_hero_id: 100524,
    name: '沙摩柯',
    pinyin: 'shamoke',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '2',
    hero_id: 100591,
    hero_type: 1,
    icon_hero_id: 100591,
    name: '钟会',
    pinyin: 'zhonghui',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '6',
    hero_id: 100731,
    hero_type: 1,
    icon_hero_id: 100591,
    name: '钟会',
    pinyin: 'zhonghui',
    quality: 5,
    season: 'SP',
    star: 5,
  },
  {
    country: '2',
    hero_id: 100603,
    hero_type: 3,
    icon_hero_id: 100603,
    name: '卞夫人',
    pinyin: 'panfuren',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '2',
    hero_id: 100449,
    hero_type: 3,
    icon_hero_id: 100449,
    name: '夏侯惇',
    pinyin: 'xiahoudun',
    quality: 5,
    season: 'XP',
    star: 5,
  },
  {
    country: '5',
    hero_id: 100557,
    hero_type: 2,
    icon_hero_id: 100557,
    name: '张梁',
    pinyin: 'zhangliang',
    quality: 5,
    season: 'SP',
    star: 5,
  },
  {
    country: '5',
    hero_id: 100562,
    hero_type: 1,
    icon_hero_id: 100562,
    name: '张宝',
    pinyin: 'zhangbao',
    quality: 5,
    season: 'SP',
    star: 5,
  },
  {
    country: '2',
    hero_id: 100585,
    hero_type: 2,
    icon_hero_id: 100585,
    name: '曹仁',
    pinyin: 'caoren',
    quality: 5,
    season: 'SP',
    star: 5,
  },
  {
    country: '5',
    hero_id: 100586,
    hero_type: 3,
    icon_hero_id: 100586,
    name: '庞德',
    pinyin: 'pangde',
    quality: 5,
    season: 'XP',
    star: 5,
  },
  {
    country: '4',
    hero_id: 100616,
    hero_type: 1,
    icon_hero_id: 100616,
    name: '凌统',
    pinyin: 'lingtong',
    quality: 5,
    season: 'XP',
    star: 5,
  },
  {
    country: '4',
    hero_id: 100671,
    hero_type: 1,
    icon_hero_id: 100671,
    name: '蒋钦',
    pinyin: 'jiangqin',
    quality: 5,
    season: 'XP',
    star: 5,
  },
  {
    country: '3',
    hero_id: 100674,
    hero_type: 2,
    icon_hero_id: 100674,
    name: '夏侯霸',
    pinyin: 'xiahouba',
    quality: 5,
    season: 'XP',
    star: 5,
  },
  {
    country: '2',
    hero_id: 100683,
    hero_type: 3,
    icon_hero_id: 100683,
    name: '曹彰',
    pinyin: 'caozhang',
    quality: 5,
    season: 'XP',
    star: 5,
  },
  {
    country: '4',
    hero_id: 100684,
    hero_type: 2,
    icon_hero_id: 100684,
    name: '程普',
    pinyin: 'chengpu',
    quality: 5,
    season: 'XP',
    star: 5,
  },
  {
    country: '3',
    hero_id: 100691,
    hero_type: 2,
    icon_hero_id: 100691,
    name: '周仓',
    pinyin: 'zhoucang',
    quality: 5,
    season: 'XP',
    star: 5,
  },
  {
    country: '1',
    hero_id: 100693,
    hero_type: 1,
    icon_hero_id: 100693,
    name: '王允',
    pinyin: 'wangyun',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '2',
    hero_id: 100769,
    hero_type: 2,
    icon_hero_id: 100769,
    name: '典韦',
    pinyin: 'dianwei',
    quality: 5,
    season: 'N',
    star: 5,
  },
];

// 材料卡池
export const material = [
  {
    country: '1',
    hero_id: 100006,
    hero_type: 2,
    icon_hero_id: 100006,
    name: '袁绍',
    pinyin: 'yuanshao',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '1',
    hero_id: 100007,
    hero_type: 3,
    icon_hero_id: 100007,
    name: '卢植',
    pinyin: 'luzhi',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '1',
    hero_id: 102004,
    hero_type: 3,
    icon_hero_id: 100007,
    name: '卢植',
    pinyin: 'luzhi',
    quality: 5,
    season: 'SP',
    star: 5,
  },
  {
    country: '5',
    hero_id: 100009,
    hero_type: 3,
    icon_hero_id: 100009,
    name: '董卓',
    pinyin: 'dongzhuo',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '2',
    hero_id: 100025,
    hero_type: 1,
    icon_hero_id: 100025,
    name: '曹丕',
    pinyin: 'caopi',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '2',
    hero_id: 100083,
    hero_type: 2,
    icon_hero_id: 100083,
    name: '张郃',
    pinyin: 'zhangxia',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '2',
    hero_id: 102013,
    hero_type: 3,
    icon_hero_id: 100083,
    name: '张郃',
    pinyin: 'zhangxia',
    quality: 5,
    season: 'SP',
    star: 5,
  },
  {
    country: '2',
    hero_id: 100310,
    hero_type: 2,
    icon_hero_id: 100310,
    name: '邓艾',
    pinyin: 'dengai',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '1',
    hero_id: 100486,
    hero_type: 3,
    icon_hero_id: 100486,
    name: '潘凤',
    pinyin: 'panfeng',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '1',
    hero_id: 100369,
    hero_type: 2,
    icon_hero_id: 100369,
    name: '华佗',
    pinyin: 'huatuo',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '5',
    hero_id: 100519,
    hero_type: 2,
    icon_hero_id: 100519,
    name: '兀突骨',
    pinyin: 'wutugu',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '4',
    hero_id: 100522,
    hero_type: 1,
    icon_hero_id: 100522,
    name: '诸葛恪',
    pinyin: 'zhugeke',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '5',
    hero_id: 100550,
    hero_type: 3,
    icon_hero_id: 100550,
    name: '轲比能',
    pinyin: 'kebineng',
    quality: 5,
    season: 'XP',
    star: 5,
  },
  {
    country: '5',
    hero_id: 100592,
    hero_type: 1,
    icon_hero_id: 100592,
    name: '董白',
    pinyin: 'dongbai',
    quality: 5,
    season: 'XP',
    star: 5,
  },
  {
    country: '5',
    hero_id: 100634,
    hero_type: 2,
    icon_hero_id: 100634,
    name: '吕姬',
    pinyin: 'lvji',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '5',
    hero_id: 100646,
    hero_type: 1,
    icon_hero_id: 100646,
    name: '于吉',
    pinyin: 'yuji',
    quality: 5,
    season: 'XP',
    star: 5,
  },
  {
    country: '2',
    hero_id: 100652,
    hero_type: 1,
    icon_hero_id: 100652,
    name: '王朗',
    pinyin: 'wanglang',
    quality: 5,
    season: 'XP',
    star: 5,
  },
  {
    country: '4',
    hero_id: 100654,
    hero_type: 1,
    icon_hero_id: 100654,
    name: '孙鲁班',
    pinyin: 'sunluban',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '2',
    hero_id: 100655,
    hero_type: 1,
    icon_hero_id: 100655,
    name: '郭皇后',
    pinyin: 'guohuanghou',
    quality: 5,
    season: 'XP',
    star: 5,
  },
];

// 纪念卡
export const commemorate = [
  {
    country: '5',
    hero_id: 100533,
    hero_type: 3,
    icon_hero_id: 100533,
    name: '率土一载',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '5',
    hero_id: 100588,
    hero_type: 3,
    icon_hero_id: 100588,
    name: '率土二载',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '5',
    hero_id: 100617,
    hero_type: 3,
    icon_hero_id: 100617,
    name: '率土三载',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '5',
    hero_id: 100650,
    hero_type: 3,
    icon_hero_id: 100650,
    name: '率土四载',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '5',
    hero_id: 100673,
    hero_type: 3,
    icon_hero_id: 100673,
    name: '率土五载',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '5',
    hero_id: 100686,
    hero_type: 3,
    icon_hero_id: 100686,
    name: '率土六载',
    quality: 5,
    season: 'N',
    star: 5,
  },
  {
    country: '5',
    hero_id: 100720,
    hero_type: 3,
    icon_hero_id: 100720,
    name: '长风破浪',
    quality: 5,
    season: 'N',
    star: 5,
  },
];

export const tenHeroId = [...jueCore].map((item) => item.hero_id); // 10分列表

export const eightHeroId = [...huang].map((item) => item.hero_id); // 8分列表

export const sevenHeroId = [...core].map((item) => item.hero_id); // 7分列表

export const sixHeroId = [...xpCore].map((item) => item.hero_id); // 6分列表

export const fiveHeroId = [...halfCore].map((item) => item.hero_id); // 5分列表

export const fourHeroId = [...xpHalfCore, ...jue].map((item) => item.hero_id); // 4分列表

export const twoHeroId = [...useful].map((item) => item.hero_id); // 2分列表

export const oneHeroId = [...normal].map((item) => item.hero_id); // 1分列表

export const commemorateName = commemorate.map((item) => item.name); // 纪念卡

// 鬼-5 S2 -3
// 诸葛亮-5
// 袁绍 关羽、马岱、田丰、李儒、大乔
// 三皇
// 吕蒙、马超、张机、群貂
// 法正、关羽、华雄
// 魏延、王异、
